
--1 
SELECT FNAME,LNAME,SALARY FROM EMPLOYEE
WHERE SALARY > 2000 AND HIRE_DATE > '15/09/1981'
ORDER BY SALARY DESC ;

--2 

SELECT * FROM CUST_ORDER
WHERE SALES_EMP_ID = 7654
AND STATUS LIKE '%DELIVERED';

--3

SELECT NAME  FROM CUSTOMER 
WHERE REGION_ID IN  (6, 10) 
AND TOT_ORDERS < 100; 

-- 4

SELECT C.NAME AS "NOMBRE_CLIENTE", R.NAME AS "REGION"
FROM CUSTOMER C
JOIN  REGION R 
ON C.REGION_ID = R.REGION_ID ;

--5

SELECT C.NAME AS "NOMBRE_CLIENTE", R.NAME AS "REGION"
FROM CUSTOMER C
JOIN  REGION R 
ON C.REGION_ID = R.REGION_ID 
WHERE C.TOT_ORDERS > 100;

--6

SELECT E.FNAME, E.LNAME, E.HIRE_DATE
FROM EMPLOYEE E
JOIN DEPARTMENT D 
ON E.DEPT_ID = D.DEPT_ID
WHERE D.NAME = 'ACCOUNTING' OR (D.NAME = 'SALES' AND E.SALARY > 1500);

--7

SELECT E.FNAME AS "NAME", E.LNAME AS "LAST_NAME", D.NAME AS "DEEPARTMENT"
FROM EMPLOYEE E
JOIN DEPARTMENT D 
ON E.DEPT_ID = D.DEPT_ID
JOIN LOCATION L 
ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.REGIONAL_GROUP = 'DALLAS';

--8

SELECT E.FNAME AS "NAME", E.LNAME AS "LAST_NAME", D.NAME AS "DEEPARTMENT"
FROM EMPLOYEE E
JOIN DEPARTMENT D 
ON E.DEPT_ID = D.DEPT_ID
JOIN LOCATION L 
ON D.LOCATION_ID = L.LOCATION_ID
JOIN JOB J 
ON J.JOB_ID = E.JOB_ID
WHERE L.REGIONAL_GROUP = 'DALLAS'
AND J.FUNCTION = 'ANALYST';

--9

SELECT C.NAME 
FROM CUSTOMER C
JOIN REGION R
ON C.REGION_ID = R.REGION_ID
WHERE R.NAME ='New England';

--10

SELECT C.NAME, E.FNAME
FROM CUSTOMER C
JOIN CUST_ORDER CO
ON C.CUST_NBR = CO.CUST_NBR
JOIN EMPLOYEE E
ON CO.SALES_EMP_ID = E.EMP_ID
JOIN REGION R
ON C.REGION_ID = R.REGION_ID
WHERE R.NAME ='New England';



