----TablasClientes



GRANT SELECT ON cliente TO ROLUFPROY;
GRANT SELECT ON tipo_cliente TO ROLUFPROY;


-- Asegúrate de estar en el esquema correcto (TABLAS_CLIENTES)
-- Nota que quitamos IDCLIENTE de la lista de columnas

INSERT INTO TABLAS_CLIENTES.cliente (NOMBRE, APELLIDO, FECHAREGISTRO, IDTIPOCLIENTE)
VALUES ('Juan', 'Perez', TO_DATE('2023-01-15','YYYY-MM-DD'), 1);

INSERT INTO TABLAS_CLIENTES.cliente (NOMBRE, APELLIDO, FECHAREGISTRO, IDTIPOCLIENTE)
VALUES ('Maria', 'Gonzalez', TO_DATE('2023-02-20','YYYY-MM-DD'), 2);

INSERT INTO TABLAS_CLIENTES.cliente (NOMBRE, APELLIDO, FECHAREGISTRO, IDTIPOCLIENTE)
VALUES ('Carlos', 'Rodriguez', TO_DATE('2023-03-10','YYYY-MM-DD'), 1);

INSERT INTO TABLAS_CLIENTES.cliente (NOMBRE, APELLIDO, FECHAREGISTRO, IDTIPOCLIENTE)
VALUES ('Ana', 'Jimenez', TO_DATE('2023-04-05','YYYY-MM-DD'), 2);

INSERT INTO TABLAS_CLIENTES.cliente (NOMBRE, APELLIDO, FECHAREGISTRO, IDTIPOCLIENTE)
VALUES ('Luis', 'Mora', TO_DATE('2023-05-18','YYYY-MM-DD'), 1);

-- ¡EL PASO FINAL QUE NO PUEDE FALTAR!
COMMIT;

