-- Creación del Perfil de Seguridad (Unidad 4 Admín)
-- Esto asegura que las contraseñas expiren y tengan complejidad profesional
CREATE PROFILE PROF_ANALISTA LIMIT
    FAILED_LOGIN_ATTEMPTS 3 -- Número máximo de intentos fallidos
    PASSWORD_LIFE_TIME 60 -- Duración de la contraseña en días


-- Creación del Usuario ANALISTA_FINANCIERO con el perfil de seguridad PROF_ANALISTA
CREATE USER ANALISTA_FINANCIERO
IDENTIFIED BY "IngSistema_2026_*"
PROFILE PROF_ANALISTA

GRANT CREATE SESSION TO ANALISTA_FINANCIERO; -- Permite al usuario iniciar sesión
GRANT CREATE TABLE TO ANALISTA_FINANCIERO; -- Permite al usuario crear tablas
GRANT CREATE VIEW TO ANALISTA_FINANCIERO; -- Permite al usuario crear vistas
GRANT CREATE PROCEDURE TO ANALISTA_FINANCIERO; -- Permite al usuario crear procedimientos almacenados
GRANT CREATE SEQUENCE TO ANALISTA_FINANCIERO; -- Permite al usuario crear secuencias

ALTER USER ANALISTA_FINANCIERO QUOTA 100M ON DATA; -- Permite al usuario usar espacio en la tablespace DATA


-- 1. CREACIÓN DE LA TABLA CON ESTÁNDAR PROFESIONAL
CREATE TABLE TBL_MOVIMIENTOS_FINANCIEROS (
    id_transaccion      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    num_cuenta          VARCHAR2(20) NOT NULL,
    tipo_movimiento     VARCHAR2(10),
    monto               NUMBER(15,2),
    fecha_operacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    codigo_sucursal     NUMBER(5),
    
    -- Restricciones de Integridad (El "Escudo" de tus datos)
    CONSTRAINT pk_movimientos PRIMARY KEY (id_transaccion),
    CONSTRAINT chk_tipo_mov CHECK (tipo_movimiento IN ('DEBITO', 'CREDITO')),
    CONSTRAINT chk_monto_positivo CHECK (monto > 0)
);

-- 2. DICCIONARIO DE DATOS (Documentación integrada)
-- Un profesional siempre deja comentarios en el catálogo de la BD.
COMMENT ON TABLE TBL_MOVIMIENTOS_FINANCIEROS IS 'Registro centralizado de transacciones para análisis de auditoría financiera.';
COMMENT ON COLUMN TBL_MOVIMIENTOS_FINANCIEROS.tipo_movimiento IS 'Solo admite valores DEBITO o CREDITO para consistencia en reportes.';

-- 3. CREACION TABLA CLIENTES

CREATE TABLE TBL_CLIENTES_BANCO (
    
    
) 

