-- ============================================================
-- 1. Drops para eliminar usuarios  y roles
--Conectar como Admin
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP USER UFPROY01 CASCADE';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER DESA10 CASCADE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TABLAS_FACTURACION CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TABLAS_MASCOTAS CASCADE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TABLAS_CLIENTES CASCADE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Limpieza de roles
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLUFPROY';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLDESAPROY';  EXCEPTION WHEN OTHERS THEN NULL; END;



-- ============================================================
-- 2. Creacion de usuarios del sistema /  y roles
-- ============================================================

-- 1. Rol del usuarios que almacenaran sus tablas


CREATE USER TABLAS_CLIENTES IDENTIFIED BY palabraPaso2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE USER TABLAS_MASCOTAS IDENTIFIED BY palabraPaso2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE USER TABLAS_FACTURACION IDENTIFIED BY palabraPaso2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;


-- 2. Privilegios asignados a los usuarios que almacenaran sus tablas

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW
TO TABLAS_CLIENTES;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW
TO TABLAS_MASCOTAS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW
TO TABLAS_FACTURACION;


--- 3. Creacion del ROl Desarrollador 

CREATE ROLE ROLDESAPROY;

GRANT CREATE SESSION, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM
TO ROLDESAPROY;

CREATE USER DESA10 IDENTIFIED BY palabraPaso2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT ROLDESAPROY TO DESA10;


-- 4. Creacion del Rol Usuario Final

CREATE ROLE ROLUFPROY;

GRANT CREATE SESSION TO ROLUFPROY;

CREATE USER UFPROY01 IDENTIFIED BY palabraPaso2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 0 ON DATA;

GRANT CREATE SYNONYM TO UFPROY01;

GRANT ROLUFPROY TO UFPROY01;


GRANT SELECT ON TABLAS_MASCOTAS.mascota TO TABLAS_CLIENTES;

GRANT SELECT, INSERT ON TABLAS_FACTURACION.cita TO TABLAS_CLIENTES;


-------------------------------------------------

-- 1. Permisos para el Módulo de Clientes
GRANT INSERT, UPDATE, DELETE ON TABLAS_CLIENTES.cliente TO ROLUFPROY;
GRANT INSERT, UPDATE, DELETE ON TABLAS_CLIENTES.tipo_cliente TO ROLUFPROY;

-- 2. Permisos para el Módulo de Mascotas 
-- (Para que el cliente pueda registrar o editar sus mascotas)
GRANT INSERT, UPDATE, DELETE ON TABLAS_MASCOTAS.mascota TO ROLUFPROY;

-- 3. Permisos para el Módulo de Facturación
-- (Normalmente aquí solo daríamos INSERT y SELECT, pero si ocupas editar:)
GRANT INSERT, UPDATE ON TABLAS_FACTURACION.cita TO ROLUFPROY;


-- Permisos sobre la tabla de bitácora
GRANT SELECT, INSERT ON TABLAS_CLIENTES.bitacora_clientes TO ROLUFPROY;

-- Permiso sobre la secuencia (indispensable para el ID automático)
GRANT SELECT ON TABLAS_CLIENTES.seq_bitacora_clientes TO ROLUFPROY;