
--- Seccion con la que se tiene que iniciar sesion como Admin o SYS

/********************************************************************************************************************************************************************/
---BORRADO DE PRUEBAS


DROP TABLESPACE TS_Banco_Financiero_Nova INCLUDING CONTENTS AND DATAFILES;
DROP USER DW_BANCO_NOVA CASCADE;
DROP USER USRCONSULTA CASCADE;
DROP USER USRDESARROLADOR CASCADE;
DROP USER USRDBA CASCADE;
DROP PROFILE PERFIL_USUARIOS;
DROP ROLE ROL_CONSULTA_APP;
DROP ROLE ROL_DESARROLLADOR_APP;
DROP ROLE ROL_DBA_APP;

/*****************************************************************************************************/

CREATE PROFILE PERFIL_USUARIOS LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_LOCK_TIME 7
    PASSWORD_REUSE_TIME 10
    SESSIONS_PER_USER 2
    IDLE_TIME 15
    CONNECT_TIME 480
    CPU_PER_SESSION 10000;

-- 2. Crear Usuarios con Contraseña Larga (Mínimo 12-15 caracteres por seguridad)
CREATE USER DW_BANCO_NOVA IDENTIFIED BY "NoVa2026_SistemaSeguro!" 
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE PERFIL_USUARIOS;

CREATE USER USRCONSULTA IDENTIFIED BY "PwUsrNova24_Segura!" 
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE PERFIL_USUARIOS;

CREATE USER USRDESARROLADOR IDENTIFIED BY "PwUsrNova24_Segura!" 
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE PERFIL_USUARIOS;

CREATE USER USRDBA IDENTIFIED BY "PwUsrNova24_Segura!" 
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE PERFIL_USUARIOS;

-- 3. Asignar Cuotas (Ahora sí funcionará porque el usuario ya existe)
ALTER USER DW_BANCO_NOVA QUOTA UNLIMITED ON TS_Banco_Financiero_Nova;
ALTER USER USRCONSULTA QUOTA UNLIMITED ON TS_Banco_Financiero_Nova;
ALTER USER USRDESARROLADOR QUOTA UNLIMITED ON TS_Banco_Financiero_Nova;
ALTER USER USRDBA QUOTA UNLIMITED ON TS_Banco_Financiero_Nova;
ALTER PROFILE PERFIL_USUARIOS LIMIT SESSIONS_PER_USER UNLIMITED;

-- 4. Grants directos al dueño
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, 
      CREATE SEQUENCE, CREATE TRIGGER TO DW_BANCO_NOVA;
      
GRANT EXECUTE ON DBMS_FGA TO DW_BANCO_NOVA;
GRANT SELECT ANY DICTIONARY TO DW_BANCO_NOVA;

/********************************************************************************************************************************************************************/

-- Creacion de roles y permisos

-- 4. Grants directos al dueño
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, 
      CREATE SEQUENCE, CREATE TRIGGER TO DW_BANCO_NOVA;
      
GRANT EXECUTE ON DBMS_FGA TO DW_BANCO_NOVA;
GRANT SELECT ANY DICTIONARY TO DW_BANCO_NOVA;
GRANT SELECT ON DBA_TAB_PRIVS TO DW_BANCO_NOVA;
GRANT SELECT ON DBA_ROLE_PRIVS TO DW_BANCO_NOVA;
GRANT SELECT ON DBA_SYS_PRIVS TO DW_BANCO_NOVA;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO DW_BANCO_NOVA; 
GRANT SELECT ON UNIFIED_AUDIT_TRAIL TO DW_BANCO_NOVA;
GRANT SELECT ON DBA_AUDIT_TRAIL TO DW_BANCO_NOVA;

-- EJECUTAR COMO ADMIN
CREATE OR REPLACE PUBLIC SYNONYM fact_producto_contrato FOR DW_BANCO_NOVA.fact_producto_contrato;
CREATE OR REPLACE PUBLIC SYNONYM dim_cliente FOR DW_BANCO_NOVA.dim_cliente;
CREATE OR REPLACE PUBLIC SYNONYM dim_sucursal FOR DW_BANCO_NOVA.dim_sucursal;
CREATE OR REPLACE PUBLIC SYNONYM dim_territorio FOR DW_BANCO_NOVA.dim_territorio;
CREATE OR REPLACE PUBLIC SYNONYM dim_estadoContrato FOR DW_BANCO_NOVA.dim_estadoContrato;
CREATE OR REPLACE PUBLIC SYNONYM dim_interacciones FOR DW_BANCO_NOVA.dim_interacciones;
CREATE OR REPLACE PUBLIC SYNONYM VW_CLIENTE_SEGURA FOR DW_BANCO_NOVA.VW_CLIENTE_SEGURA;

-- ROL CONSULTA

-- Ejecutar como ADMIN
DROP ROLE ROL_CONSULTA_APP;
CREATE ROLE ROL_CONSULTA_APP;
GRANT CREATE SESSION TO ROL_CONSULTA_APP;
GRANT ROL_CONSULTA_APP TO USRCONSULTA;


CREATE OR REPLACE PUBLIC SYNONYM fact_producto_contrato FOR DW_BANCO_NOVA.fact_producto_contrato;
CREATE OR REPLACE PUBLIC SYNONYM dim_cliente FOR DW_BANCO_NOVA.dim_cliente;
CREATE OR REPLACE PUBLIC SYNONYM dim_sucursal FOR DW_BANCO_NOVA.dim_sucursal;
CREATE OR REPLACE PUBLIC SYNONYM dim_territorio FOR DW_BANCO_NOVA.dim_territorio;
CREATE OR REPLACE PUBLIC SYNONYM dim_estadoContrato FOR DW_BANCO_NOVA.dim_estadoContrato;
CREATE OR REPLACE PUBLIC SYNONYM dim_interacciones FOR DW_BANCO_NOVA.dim_interacciones;

-- ROL DESARROLLADOR
CREATE ROLE ROL_DESARROLLADOR_APP;
GRANT CREATE SESSION TO ROL_DESARROLLADOR_APP;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO ROL_DESARROLLADOR_APP;
GRANT EXECUTE ANY PROCEDURE TO ROL_DESARROLLADOR_APP; -- Para probar el SP del dueño
GRANT ROL_DESARROLLADOR_APP TO USRDESARROLADOR;

-- ROL DBA
CREATE ROLE ROL_DBA_APP;
GRANT CREATE SESSION TO ROL_DBA_APP;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE TO ROL_DBA_APP;
GRANT ALTER ANY TABLE, DROP ANY TABLE, SELECT ANY TABLE TO ROL_DBA_APP;
GRANT SELECT ANY DICTIONARY TO ROL_DBA_APP; -- Para reportes de auditoría
GRANT ROL_DBA_APP TO USRDBA;



-- ¿Existe el rol realmente?
SELECT * FROM DBA_ROLES WHERE ROLE = 'ROL_CONSULTA_APP';

-- ¿Tiene permisos el rol?
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ROL_CONSULTA_APP';