--DB_Tarea2
SELECT * 
FROM CITAS;

--1 
SELECT D.NOMBREDOCTOR 
FROM DOCTORES D
JOIN CITAS C ON D.IDDOCTOR = C.DOCTOR
JOIN PACIENTES P ON C.PACIENTE = P.IDPACIENTE 
JOIN CONSULTORIOS CO ON C.CONSULTORIO = CO.IDCONSULTORIO
WHERE D.SALARIO > 7000 
  AND P.PROVINCIA IN ('SAN JOSE', 'PUNTARENAS') 
  AND P.SEXO = 'M' 
  AND CO.TAMANO = 'MEDIANO' 
  AND C.FECHA > '2005-01-01'; 

--2

SELECT CO.TAMANO, COUNT(*) AS TOTAL_CITAS
FROM CONSULTORIOS CO
JOIN CITAS C ON C.CONSULTORIO = CO.IDCONSULTORIO
GROUP BY CO.TAMANO;

--3

SELECT EP.DESCRIPCIONESPECIALIDAD, COUNT(*) AS TOTAL_CITAS
FROM CITAS C
JOIN DOCTORES D ON C.DOCTOR = D.IDDOCTOR
JOIN ESPECIALIDADESMEDICAS EP ON D.ESPECIALIDAD = EP.IDESPECIALIDAD
WHERE D.SALARIO > 5000
GROUP BY EP.DESCRIPCIONESPECIALIDAD
ORDER by TOTAL_CITAS DESC;

--4 
 
SELECT P.PROVINCIA, COUNT(*) AS TOTAL_CITAS
FROM PACIENTES P
JOIN CITAS C ON C.PACIENTE = P.IDPACIENTE
WHERE P.PROVINCIA IN ('CARTAGO','GUANACASTE')
    AND P.SEXO = 'F'
GROUP BY P.PROVINCIA;

--5

SELECT 
    SUM(D.SALARIO) AS Suma_Total, 
    AVG(D.SALARIO) AS Promedio_Salarial, 
    MAX(D.SALARIO) AS Salario_Maximo, 
    MIN(D.SALARIO) AS Salario_Minimo
FROM DOCTORES D
JOIN CITAS C ON D.IDDOCTOR = C.DOCTOR
JOIN CONSULTORIOS CO ON C.CONSULTORIO = CO.IDCONSULTORIO
WHERE CO.TAMANO = 'MEDIANO';

SELECT D.NOMBREDOCTOR, D.SALARIO, CO.TAMANO
FROM DOCTORES D
JOIN CITAS C ON D.IDDOCTOR = C.DOCTOR
JOIN CONSULTORIOS CO ON C.CONSULTORIO = CO.IDCONSULTORIO
WHERE CO.TAMANO LIKE '%EDIANO%';

--6

SELECT TAMANO, COUNT(*) AS CANTIDAD_CONSULTORIO
FROM CONSULTORIOS
GROUP BY TAMANO
ORDER BY CANTIDAD_CONSULTORIO DESC; 


--7 

SELECT D.NAME, COUNT(*) AS CANTIDAD_EMPLEADOS
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.NAME
ORDER BY CANTIDAD_EMPLEADOS DESC;

--8

SELECT CU.NAME, COUNT(CO.ORDER_NBR) AS TOTAL_ORDENES
FROM CUSTOMER CU
JOIN CUST_ORDER CO ON CU.CUST_NBR = CO.CUST_NBR 
GROUP BY CU.NAME
HAVING COUNT(CO.ORDER_NBR) > 5;

--9

SELECT D.NAME, SUM(E.SALARY) AS SALARIOS_DEPARTAMENTO
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.NAME
ORDER BY SALARIOS_DEPARTAMENTO DESC;

--10

SELECT J.FUNCTION, SUM(E.SALARY) AS SALARIOS_PUESTO
FROM EMPLOYEE E 
LEFT JOIN JOB J ON E.JOB_ID = J.JOB_ID 
GROUP BY J.FUNCTION
ORDER BY SALARIOS_PUESTO DESC;

